version: '2'
services:
  cli:
    volumes_from:
      - container:amazeeio-ssh-agent
    environment:
      - XDEBUG_ENABLE=true
    volumes:
      - .:/app:delegated
  nginx:
    networks:
      - amazeeio-network
    environment:
      - AMAZEEIO_URL=mysite.docker.amazee.io
      - AMAZEEIO=AMAZEEIO
      - AMAZEEIO_HTTP_PORT=8080
    volumes:
      - .:/app:delegated
  php:
    environment:
      - XDEBUG_ENABLE=true
    volumes:
      - .:/app:delegated
  mariadb:
    ports:
      - 13306:3306
  selenium:
    image: selenium/standalone-chrome
    depends_on:
      - cli
networks:
  amazeeio-network:
    external: true
