version: '2'
services:
  cli:
    build:
      context: .
      dockerfile: Dockerfile.cli
    image: cli
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    networks:
      - default
    depends_on:
      - cli
    expose:
      - "8080"
  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    depends_on:
      - cli
  mariadb:
    image: amazeeio/centos7-mariadb10-drupal
  redis:
    image: amazeeio/redis
    labels:
      lagoon.type: redis
