version: '2'
services:
  cli:
    volumes:
      - .:/app/docroot/sites/default/files
  php:
    volumes:
      - .:/app/docroot/sites/default/files
  nginx:
    volumes:
      - .:/app/docroot/sites/default/files
  selenium:
    image: selenium/standalone-chrome
    depends_on:
      - cli
