version: 2
jobs:
  build_dependencies:
    docker:
      - image: circleci/php:7.0-cli
        environment:
          BUILD_DIR: project
          DOCROOT_DIR: /home/circleci/project/docroot
          DB_NAME: circle_test
          DB_USER: ubuntu
          DB_PASS: ubuntu
          DB_HOST: 127.0.0.1
          # Server configuration.
          SERVER: local.mysiteurl
          WEB_URL: http://local.mysiteurl
          WEB_USER: $(whoami)
          WEB_GROUP: www-data
          PHP_EXECUTABLE: $(which php)

    steps:
      - checkout
      - restore_cache:
          keys:
            - composer-dependencies1-{{ checksum "composer.json" }}-{{ checksum "package.json" }}-
      - run: composer install -n --prefer-dist
      - save_cache:
          paths:
            - ~/project/vendor
            - ~/project/node_modules
          key: composer-dependencies1-{{ checksum "composer.json" }}-{{ checksum "package.json" }}-{{ epoch }}

      - persist_to_workspace:
          root: /home/circleci
          paths:
            - project

  # Download DB.
  download_db:
    machine: true

    steps:
      - restore_cache:
          keys:
            - data-{{ .Branch }}

      # Download DB dump from public URL to test Drupal-dev project.
      # Remove the line below in your project.
      - run: if [ ! -f .data/db.dist.sql ] ; then mkdir .data && curl -L https://goo.gl/WFtJbT -o .data/db.dist.sql; fi
      # [META] Uncomment the line below to download DB dump from FTP, using
      # variables set in Circle CI UI.
      # - run: if [ ! -f $BUILD_DIR/.data/db.dist.sql ] ; then mkdir $BUILD_DIR/.data && curl -u $FTP_USER:$FTP_PASS "ftp://$FTP_HOST/db_d7.dist.sql" -o $BUILD_DIR/.data/db.dist.sql; fi

      - save_cache:
          paths:
            - ~/project/.data
          key: data-{{ .Branch }}

      - persist_to_workspace:
          root: /home/circleci
          paths:
            - project/.data/db.dist.sql

  # Code style checking.
  # Fail fast if code style is incorrect.
  code_style:
    docker:
      - image: circleci/php:7.0-cli

    steps:
      - attach_workspace:
          at: /home/circleci
      - run: composer cs
#
#  # Build.
#  build:
#    docker:
#      - image: circleci/php:7.1-apache
#        environment:
#          MYSQL_HOST: 127.0.0.1
#
#      - image: mysql:5.7
#        environment:
#          MYSQL_USER: ubuntu
#          MYSQL_PASSWORD: ubuntu
#          MYSQL_DATABASE: circle_test
#          MYSQL_ROOT_PASSWORD: ubuntu
#          MYSQL_ALLOW_EMPTY_PASSWORD: true
#          MYSQL_ROOT_HOST: "127.0.0.1"
#
#    steps:
#      - run:
#          name: Install additional binaries
#          command: |
#            sudo apt-get -y install vim mysql-client libpng-dev
#      - run:
#          name: Install PHP extensions
#          command: |
#            sudo docker-php-ext-install pdo_mysql
#            sudo docker-php-ext-install gd
#
#      - run:
#          name: Display versions
#          command: |
#            php -v
#            composer -v
#            composer config --global --list
#
#
#      - run: echo 'export PATH=~/.composer/vendor/bin:$PATH' >> $BASH_ENV
#
#      - attach_workspace:
#          at: /home/circleci
#
#      # Install drush.
#      - run: composer global require --no-interaction drush/drush
#
#      # Create local drush alias to make sure that composer build, which relies
#      # on aliases when importing DB, work correctly.
#      - run:
#          name: Create local drush alias
#          command: mkdir -p $HOME/.drush && echo "<?php \$aliases['$SERVER'] = ['uri' => '$SERVER', 'root' => '$DOCROOT_DIR'];" > $HOME/.drush/$SERVER.aliases.drushrc.php && drush sa && cat $HOME/.drush/$SERVER.aliases.drushrc.php
#          environment:
#            SERVER: local.mysiteurl
#            DOCROOT_DIR: /home/circleci/project/docroot
#
#      # @debug
#      - run: cat docroot/sites/default/settings.beetbox.php
#
#      # Run actual project build.
#      - run: composer build
#
#      # Check that Drupal can be bootstrapped after updates.
#      - run: drush status --root=$DOCROOT_DIR | grep -aqoi "Drupal bootstrap\s*:\s*Successful"
#
#  # Run tests.
#  test_behat:
#    docker:
#      - image: circleci/php:7.0-cli
#
#    steps:
#      - run: echo "Placeholder for Behat test runner"
#
#  # Deploy primary branches.
#  deploy_primary:
#    machine: true
#    steps:
#      - run: echo "Running deployment command for 'primary' branches"
#
#  # Deploy feature branches.
#  deploy_features:
#    machine: true
#    steps:
#      - run: echo "Running deployment command for 'feature' branches"

workflows:
  version: 2

  cs_and_build_and_test:
    jobs:
      - build_dependencies
      - download_db
      - code_style:
          requires:
            - build_dependencies
#      - build:
#          requires:
#            - build_dependencies
#            - download_db
#            - code_style
#      - test_behat:
#          requires:
#            - build
#      - deploy_primary:
#          requires:
#            - test_behat
#          filters:
#            branches:
#              only: /master|develop|ci|(release\/)?[0-9]+(\.[0-9]+)+(-rc[0-9]+)?|(hotfix\/)?[0-9]+(\.[0-9]+)+(-rc[0-9]+)?/
#      - deploy_features:
#          requires:
#            - test_behat
#          filters:
#            branches:
#              only: /feature\/[a-zA-z0-9\-]+/
