# YAML supports anchors and references.
# @see http://blog.daemonl.com/2016/02/yaml.html
version: 2

references:
  workspace_root: &workspace_root
    /home/circleci/project

  code_root: &code_root
    "*workspace_root/code"

  data_root: &data_root
    "*workspace_root/data"

  # Configuration shared between all containers.
  container_config: &container_config
    docker:
      - image: circleci/php:7.0-cli

    working_directory: *workspace_root

    environment:
      WORKSPACE_ROOT: *workspace_root
      CODE_ROOT: *code_root
      DATA_ROOT: *data_root

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

jobs:
  code_dependencies:
    <<: *container_config

    steps:
      - checkout:
          path: *code_root

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - *code_root

      - run: ls -al $WORKSPACE_ROOT

  # Download DB.
  download_db:
    <<: *container_config

    steps:
      - run: mkdir -p $DATA_ROOT
      - run: touch $DATA_ROOT/database.txt

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - *data_root

      - run: ls -al $WORKSPACE_ROOT

  # Code style checking.
  # Fail fast if code style is incorrect.
  code_style:
    <<: *container_config

    steps:
      - *attach_workspace

      - run: test -d $CODE_ROOT
      - run: test -d $DATA_ROOT
#
#  # code.
#  code:
#    docker:
#      - image: circleci/php:7.1-apache
#        environment:
#          MYSQL_HOST: 127.0.0.1
#
#      - image: mysql:5.7
#        environment:
#          MYSQL_USER: ubuntu
#          MYSQL_PASSWORD: ubuntu
#          MYSQL_DATABASE: circle_test
#          MYSQL_ROOT_PASSWORD: ubuntu
#          MYSQL_ALLOW_EMPTY_PASSWORD: true
#          MYSQL_ROOT_HOST: "127.0.0.1"
#
#    steps:
#      - run:
#          name: Install additional binaries
#          command: |
#            sudo apt-get -y install vim mysql-client libpng-dev
#      - run:
#          name: Install PHP extensions
#          command: |
#            sudo docker-php-ext-install pdo_mysql
#            sudo docker-php-ext-install gd
#
#      - run:
#          name: Display versions
#          command: |
#            php -v
#            composer -v
#            composer config --global --list
#
#
#      - run: echo 'export PATH=~/.composer/vendor/bin:$PATH' >> $BASH_ENV
#
#      - attach_code:
#          at: /home/circleci
#
#      # Install drush.
#      - run: composer global require --no-interaction drush/drush
#
#      # Create local drush alias to make sure that composer code, which relies
#      # on aliases when importing DB, work correctly.
#      - run:
#          name: Create local drush alias
#          command: mkdir -p $HOME/.drush && echo "<?php \$aliases['$SERVER'] = ['uri' => '$SERVER', 'root' => '$DOCROOT_DIR'];" > $HOME/.drush/$SERVER.aliases.drushrc.php && drush sa && cat $HOME/.drush/$SERVER.aliases.drushrc.php
#          environment:
#            SERVER: local.mysiteurl
#            DOCROOT_DIR: code/docroot
#
#      # @debug
#      - run: cat docroot/sites/default/settings.beetbox.php
#
#      # Run actual project/code code.
#      - run: composer code
#
#      # Check that Drupal can be bootstrapped after updates.
#      - run: drush status --root=$DOCROOT_DIR | grep -aqoi "Drupal bootstrap\s*:\s*Successful"
#
#  # Run tests.
#  test_behat:
#    docker:
#      - image: circleci/php:7.0-cli
#
#    steps:
#      - run: echo "Placeholder for Behat test runner"
#
#  # Deploy primary branches.
#  deploy_primary:
#    machine: true
#    steps:
#      - run: echo "Running deployment command for 'primary' branches"
#
#  # Deploy feature branches.
#  deploy_features:
#    machine: true
#    steps:
#      - run: echo "Running deployment command for 'feature' branches"

workflows:
  version: 2

  cs_and_code_and_test:
    jobs:
      - code_dependencies
      - download_db
      - code_style:
          requires:
            - code_dependencies
            - download_db
#      - code:
#          requires:
#            - code_dependencies
#            - download_db
#            - code_style
#      - test_behat:
#          requires:
#            - code
#      - deploy_primary:
#          requires:
#            - test_behat
#          filters:
#            branches:
#              only: /master|develop|ci|(release\/)?[0-9]+(\.[0-9]+)+(-rc[0-9]+)?|(hotfix\/)?[0-9]+(\.[0-9]+)+(-rc[0-9]+)?/
#      - deploy_features:
#          requires:
#            - test_behat
#          filters:
#            branches:
#              only: /feature\/[a-zA-z0-9\-]+/
