# YAML supports anchors and references.
# @see http://blog.daemonl.com/2016/02/yaml.html
#
# @todo:
# - optimize apache config
# - add public dir preparation to build step
version: 2

references:
  # Variables.
  workspace_root:     &workspace_root     /home/circleci/project
  code_dir:           &code_dir           code
  code_root:          &code_root          /home/circleci/project/code
  web_dir:            &web_dir            docroot
  web_root:           &web_root           /home/circleci/project/code/docroot
  data_dir:           &data_dir           data
  data_root:          &data_root          /home/circleci/project/data
  artifacts_root:     &artifacts_root     /tmp/artifacts
  server:             &server             local.mysiteurl
  web_url:            &web_url            http://local.mysiteurl
  deps_cache_key:     &deps_cache_key     v2-dependencies-{{ checksum "composer.json" }}-{{ epoch }}
  deps_cache_key_any: &deps_cache_key_any v2-dependencies-{{ checksum "composer.json" }}

  # Configuration shared between all containers.
  container_config: &container_config
    working_directory: /home/circleci/project/code

    environment: &container_config_environment
      WORKSPACE_ROOT: *workspace_root
      CODE_ROOT: *code_root
      DATA_ROOT: *data_root
      WEB_ROOT: *web_root
      SERVER: *server
      WEB_URL: *web_url
      MYSQL_USER: ubuntu
      MYSQL_PASSWORD: ubuntu
      MYSQL_DATABASE: circle_test
      MYSQL_HOST: 127.0.0.1
      MYSQL_ROOT_PASSWORD: ubuntu
      MYSQL_ROOT_HOST: 127.0.0.1
      ARTIFACTS_ROOT: *artifacts_root

    docker:
      - image: circleci/php:7.1-apache-browsers
        environment:
          <<: *container_config_environment
      - image: mysql:5.7
        environment:
          <<: *container_config_environment

  # Re-usable steps.
  step_attach_workspace: &step_attach_workspace
    attach_workspace:
      at: /home/circleci/project

  step_common: &step_common
    run:
      name: Apply common configuration
      command: |
        echo 127.0.0.1 $SERVER | sudo tee -a /etc/hosts
        echo 'export PATH=$HOME/.composer/vendor/bin:$PATH' >> $HOME/.bashrc
        echo 'export PATH=$HOME/.composer/vendor/bin:$PATH' >> $BASH_ENV
        mkdir $ARTIFACTS_ROOT
        echo 'export BEHAT_SCREENSHOT_DIR=$ARTIFACTS_ROOT/behat' >> $BASH_ENV
        printenv

  step_symlink_data: &step_symlink_data
    run:
      name: Symlink data into local data directory.
      command: ln -s $DATA_ROOT $CODE_ROOT/.data

  step_drush_alias: &step_drush_alias
    run:
      name: Create local drush alias
      command: mkdir -p $HOME/.drush && echo "<?php \$aliases['$SERVER'] = ['uri' => '$SERVER', 'root' => '$WEB_ROOT'];" > $HOME/.drush/$SERVER.aliases.drushrc.php && composer drush -- sa && cat $HOME/.drush/$SERVER.aliases.drushrc.php

jobs:
  code_dependencies:
    <<: *container_config
    steps:
      - *step_common
      - *step_attach_workspace

      # @debug
      - run: printenv

      - checkout
      # @debug
      - run: test -d $WEB_ROOT/sites

      - restore_cache:
          keys:
            - *deps_cache_key_any

      - run:
          name: Install dependencies
          command: composer install -n --prefer-dist

      - save_cache:
          paths:
          # @note: We do not cache vendor dir as this prevent Drupal core files
          # from being built on the next run and we cannot cache the whole
          # docroot as it contains excluded files.
            - $HOME/.composer/cache
          key: *deps_cache_key

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - *code_dir

      # Validate step results.
      # @debug
      - run: test -d $HOME/.composer/cache
      - run: test -d /home/circleci/project/code/vendor
      - run: test -d /home/circleci/project/code/node_modules
      - run: test -f /home/circleci/project/code/docroot/index.php
      - run: cat /home/circleci/project/code/docroot/sites/default/settings.beetbox.php

  # Download DB.
  download_db:
    <<: *container_config
    working_directory: /home/circleci/project
    steps:
      - *step_common
      - restore_cache:
          keys:
            - v1-data-{{ .Branch }}

      # Download DB dump from public URL to test Drupal-dev project/build.
      # Remove the line below in your project/build.
      - run: if [ ! -f $DATA_ROOT/db.dist.sql ] ; then mkdir -p $DATA_ROOT && curl -L https://goo.gl/WFtJbT -o $DATA_ROOT/db.dist.sql; fi
      # [META] Uncomment the line below to download DB dump from FTP, using
      # variables set in Circle CI UI.
      # - run: if [ ! -f $DATA_ROOT/db.dist.sql ] ; then mkdir -p $DATA_ROOT && curl -u $FTP_USER:$FTP_PASS "ftp://$FTP_HOST/db.dist.sql" -o $DATA_ROOT/db.dist.sql; fi

      - save_cache:
          paths:
            - *data_dir
          key: v1-data-{{ .Branch }}

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - *data_dir

      # Validate step results.
      # @debug
      - run: test -f /home/circleci/project/data/db.dist.sql

  # Code style checking.
  # Fail fast if code style is incorrect.
  code_style:
    <<: *container_config
    steps:
      - *step_common
      - *step_attach_workspace

      # Validate step pre-requisites.
      # @debug
      - run: test -d /home/circleci/project/code/vendor
      - run: test -d /home/circleci/project/code/node_modules
      - run: test -f /home/circleci/project/code/docroot/index.php
      - run: test -d /home/circleci/project/code/docroot/sites/all/modules/custom

      - run:
          name: Lint code
          command: composer cs

      - run: test -d /home/circleci/project/code

  # Build.
  build:
    <<: *container_config
    steps:
      - *step_common
      - *step_attach_workspace

      # Validate step pre-requisites.
      # @debug
      - run: test -d /home/circleci/project/code/vendor
      - run: test -d /home/circleci/project/code/node_modules
      - run: test -f /home/circleci/project/code/docroot/index.php
      - run: test -f /home/circleci/project/data/db.dist.sql
      - run: test -f /home/circleci/project/code/docroot/sites/default/settings.beetbox.php
      - run: cat /home/circleci/project/code/docroot/sites/default/settings.beetbox.php
      - run: printenv

      - run:
          name: Install additional binaries
          command: |
            sudo apt-get -y install vim mysql-client libpng-dev

      # @debug
      - run: mysql -h 127.0.0.1 -u ubuntu -pubuntu --database=circle_test -e"quit"

      - run:
          name: Install PHP extensions
          command: |
            sudo docker-php-ext-install pdo_mysql
            sudo docker-php-ext-install gd

      - run:
          name: Display versions
          command: |
            php -v
            composer -v
            composer drush -- -v
            composer config --global --list

      - *step_drush_alias
      - *step_symlink_data

      # @debug
      - run: test -L $CODE_ROOT/.data
      - run: test -f $CODE_ROOT/.data/db.dist.sql

      # Run actual project build.
      - run: composer build

      # @debug
      - run: composer drush status -- --root=$WEB_ROOT

      - run:
          name: Check that Drupal can be bootstrapped.
          command: composer drush status -- --root=$WEB_ROOT | grep -aqoi "Drupal bootstrap\s*:\s*Successful"

      - run:
          name: Store built DB as an artifact.
          command: composer drush -- --root=$WEB_ROOT sql-dump > .data/db.sql

      # @debug
      - run: test -f $CODE_ROOT/.data/db.sql

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - *data_dir

  # Run tests.
  test_behat:
    <<: *container_config

    # Increase this value to run tests in parallel.
    parallelism: 1

    steps:
      - *step_common
      - *step_attach_workspace

#      - run: sudo usermod -a -G circleci www-data
#      - run: sudo chmod -Rf 755 $WORKSPACE_ROOT

      # Validate step pre-requisites.
      # @debug
      - run: test -d /home/circleci/project/code/vendor
      - run: test -d /home/circleci/project/code/node_modules
      - run: test -f /home/circleci/project/code/docroot/index.php
      - run: test -f /home/circleci/project/data/db.dist.sql
      - run: test -f /home/circleci/project/code/docroot/sites/default/settings.beetbox.php
      - run: cat /home/circleci/project/code/docroot/sites/default/settings.beetbox.php
      - run: printenv

      - run:
          name: Install additional binaries
          command: |
            sudo apt-get -y install vim mysql-client libpng-dev

      # @debug
      - run: mysql -h 127.0.0.1 -u ubuntu -pubuntu --database=circle_test -e"quit"

      - run:
          name: Install PHP extensions
          command: |
            sudo docker-php-ext-install pdo_mysql
#            sudo docker-php-ext-install gd

      - run:
          name: Display versions
          command: |
            php -v
            composer -v
            composer config --global --list

      - *step_drush_alias
      - *step_symlink_data

      # @debug
      - run: test -f $CODE_ROOT/.data/db.sql

      - run:
          name: Import previously built DB
#          command: composer drush -- @local.mysiteurl sql-cli < $CODE_ROOT/.data/db.sql
          command: vendor/bin/drush @local.mysiteurl sql-cli < $CODE_ROOT/.data/db.sql

      - run:
          name: Check that Drupal can be bootstrapped.
          command: composer drush status -- --root=$WEB_ROOT | grep -aqoi "Drupal bootstrap\s*:\s*Successful"

      - run: |
            echo "
            <VirtualHost *:80>
              UseCanonicalName Off
              DocumentRoot %DOCROOT%
              ServerName %SERVER%
              <Directory %DOCROOT%>
                Options FollowSymLinks
                AllowOverride All
                RewriteEngine On
                RewriteBase /
                RewriteCond %{REQUEST_FILENAME} !-f
                RewriteCond %{REQUEST_FILENAME} !-d
                RewriteRule %DOCROOT%/(.*)$ index.php/?q=$1 [L,QSA]
                Require all granted
              </Directory>
            </VirtualHost>" > apache-vhost.conf
      - run: |
          sudo sed -e "s?%DOCROOT%?$WEB_ROOT?g" --in-place apache-vhost.conf
          sudo sed -e "s?%SERVER%?$SERVER?g" --in-place apache-vhost.conf
          sudo cp apache-vhost.conf /etc/apache2/sites-available/000-default.conf

      # @debug
      - run: cat /etc/apache2/sites-available/000-default.conf

      - run: sudo a2enmod rewrite && sudo a2enmod proxy_http
      - run: sudo service apache2 stop && sudo service apache2 start
      # Validate that Apache can serve PHP pages.
      - run: echo "<?php phpinfo();" > $WEB_ROOT/info.php && curl -k -s -o info.html $WEB_URL/info.php && cat info.html | grep -aqoi "Build Date" && cat info.html && rm $WEB_ROOT/info.php && rm info.html;

      - run:
          name: Download Selenium
          command: curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar

      - run:
          name: Start Selenium
          command: java -jar selenium-server-standalone-3.5.3.jar -log $ARTIFACTS_ROOT/selenium.log
          background: true

      - run: echo $BEHAT_SCREENSHOT_DIR

      - run:
          name: Run Behat tests
          command: |
            composer test

      - store_artifacts:
          path: *artifacts_root

  # Deploy primary branches.
  deploy_primary:
    <<: *container_config
    steps:
      - run: echo "Running deployment command for 'primary' branches"

  # Deploy feature branches.
  deploy_features:
    <<: *container_config
    steps:
      - run: echo "Running deployment command for 'feature' branches"

workflows:
  version: 2

  main:
    jobs:
      - code_dependencies
      - download_db
#      - code_style:
#          requires:
#            - code_dependencies
      - build:
          requires:
            - code_dependencies
            - download_db
#            - code_style
      - test_behat:
          requires:
            - build
      - deploy_primary:
          requires:
            - test_behat
          filters:
            branches:
              only: /master|develop|ci|(release\/)?[0-9]+(\.[0-9]+)+(-rc[0-9]+)?|(hotfix\/)?[0-9]+(\.[0-9]+)+(-rc[0-9]+)?/
      - deploy_features:
          requires:
            - test_behat
          filters:
            branches:
              only: /feature\/[a-zA-z0-9\-]+/
