version: 2
jobs:
  build:
    docker:
    - image: integratedexperts/ci-builder
    working_directory: /app
    steps:
    - checkout
    - run:
        name: Check spelling
        command: ./check-spell.sh ./docs/README.md
