#:
#: CircleCI 2.0 configuration file.
#:
#: Understanding CircleCI 'docker' executor.
#:
#: CircleCI uses "runner" container (created from specified Docker image)
#: to checkout source code and run commands defined in this file.
#: Application Docker containers (the ones defined in docker-compose.yml)
#: run on *remote* docker server, started by CircleCI as a part of their stack.
#: The "runner" container uses Docker client to control remote Docker server
#: (when used locally, Docker bundles both client and server into a single
#: "Docker" application, so you may not even know that these are two different
#: services).
#:
#: Because Docker images use layers, it is possible to cache Docker images
#: between builds to significantly speedup application provisioning for each
#: job (it requires enabling of Docker Layer Caching feature in CircleCI by
#: lodging a support request).
#: https://circleci.com/docs/2.0/docker-layer-caching/
#;
#; Comments starting with '#;', '#;<' or '#;>' (like the ones used for the
#; current paragraph) are explaining DrevOps inner workings and can be safely
#; removed for your project. They are automatically removed when installing
#; or updating DrevOps.
version: 2

#:###############################################################################
#: VARIABLES
#:###############################################################################
#: For YAML support of anchors and references, see http://blog.daemonl.com/2016/02/yaml.html
aliases:
  #:-----------------------------------------------------------------------------
  #: Per-project variables.
  #:-----------------------------------------------------------------------------

  # Timezone of the runner container to ensure that DB cache key uses correct date.
  #; Replace this timezone with your own.
  #; @see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  - &timezone "Australia/Melbourne"

  # SSH key fingerprint to deploy code.
  #: Generate a separate SSH key for a user who has push permissions to
  #: $DEPLOY_GIT_REMOTE repo with `ssh-keygen -m PEM -t rsa -C "deployer@example.com"
  #: command and add private key under "SSH Permissions" in CircleCI UI.
  #;
  #; This is a fingerprint of the key to push DrevOps project itself as an example.
  #; Replace this key fingerprint with your own.
  - &deploy_ssh_fingerprint "56:f3:3f:51:c3:8f:b3:75:01:90:6e:26:48:e7:48:e1"

  #:-----------------------------------------------------------------------------
  #: Optional variables.
  #:-----------------------------------------------------------------------------

  # How often to refresh the cache of the database. Refer to `date` command.
  - &db_cache_timestamp +%Y_%m_%d

  # Use previous database caches on this branch as a fallback if the above cache
  # does not match. Only allowed "yes" or "no" (include enclosing double quotes).
  - &db_cache_fallback "yes"

  # Database cache directory.
  - &db_cache_dir /root/project/.data

  # CI runner resource class.
  # @see https://circleci.com/docs/2.0/configuration-reference/#resource_class
  # Change to 'large' for faster builds. Requires lodging a support request
  # with CircleCI o enable this feature.
  - &resource_class medium

  # Docker Layer Caching allows to significantly speed up builds by caching
  # images built during previous runs.
  # @see https://circleci.com/docs/2.0/docker-layer-caching/
  # Change to 'true' (without single quotes) to enable. Requires lodging a
  # support request with CircleCI o enable this feature.
  - &docker_layer_caching false

  #:-----------------------------------------------------------------------------

  #: Shared configuration applied to each job.
  - &container_config
    #:
    #: Location of checked-out files within "runner" container.
    working_directory: &working_directory /root/project
    environment:
      DEPLOY_SSH_FINGERPRINT: *deploy_ssh_fingerprint
    docker:
      #; Using "runner" container where each job will be executed. This container
      #; has all necessary tools to run dockerized environment.
      #; @see https://github.com/drevops/ci-builder
      - image: drevops/ci-builder
        environment:
          # Set timezone to ensure that executed operations use correct timestamps.
          TZ: *timezone
          # Volumes mounting to host is not supported in CircleCI.
          VOLUMES_MOUNTED: 0
          # Always answer 'y' to any confirmation questions.
          CONFIRM_RESPONSE: 'y'
          # How often to refresh the cache of the DB dump. Refer to `date` command.
          DB_CACHE_TIMESTAMP: *db_cache_timestamp
          # Use cache fallback if the above timestamp does not match.
          DB_CACHE_FALLBACK: *db_cache_fallback
          # Directory to store code exported between jobs.
          BUILD_EXPORT_DIR: &build_export_dir /workspace/code
          # Directory to store test results.
          TEST_LOG_DIR: &test_log_dir /tmp/tests
          # Directory to store test artifacts.
          TEST_ARTIFACT_DIR: &test_artifact_dir /tmp/artifacts
          # Use compact error reporting format.
          BEHAT_FORMAT: progress_fail
          # Directory to use for code deployments.
          DEPLOY_CODE_SRC: *build_export_dir
          # Source code location.
          DEPLOY_CODE_ROOT: *working_directory
          # Deployment report file location.
          DEPLOY_REPORT: /tmp/artifacts/deployment_report.txt
          # Check only minimal stack requirements.
          DOCTOR_CHECK_MINIMAL: 1
    resource_class: *resource_class

  # Step to setup remote docker.
  - &step_setup_remote_docker
    setup_remote_docker:
      docker_layer_caching: *docker_layer_caching
  # Step to process the codebase to be ran in CI environment.
  - &step_process_codebase
    run:
      name: Process codebase to run in CI
      #: Remove lines containing '###' and uncomment comments starting with '##'.
      command: sed -i -e "/###/d" docker-compose.yml && sed -i -e "s/##//" docker-compose.yml

#:###############################################################################
#: JOBS
#:###############################################################################
jobs:
  #: Database handling is a first step of the build.
  #:
  #: $DB_CACHE_TIMESTAMP is used to determine if a fresh DB dump should be
  #: downloaded for the current build. Usually, a daily database dump is
  #: sufficient for development activities.
  #:
  #: $DB_CACHE_FALLBACK is used if the cache did not match $DB_CACHE_TIMESTAMP.
  #: This allows to rely on the cache from the previous days within the same
  #: branch.
  #:
  #: Database will be sanitized using standard drush sanitization. You may also
  #: use custom SQL script to add more sanitization steps by putting SQL
  #: statements into scripts/sanitize.sql file.
  #;< !FRESH_INSTALL
  database:
    <<: *container_config
    steps:
      - attach_workspace:
          at: /workspace
      - checkout
      - *step_process_codebase
      - *step_setup_remote_docker
      - run:
          name: Set timestamp for database caching
          command: |
            echo "echo $CIRCLE_WORKFLOW_ID $(date ${DB_CACHE_TIMESTAMP})" > /tmp/DB_CACHE_TIMESTAMP && cat /tmp/DB_CACHE_TIMESTAMP
            echo "echo $CIRCLE_WORKFLOW_ID ${DB_CACHE_FALLBACK/no/${CIRCLE_BUILD_NUM}}" > /tmp/DB_CACHE_FALLBACK && cat /tmp/DB_CACHE_FALLBACK
      - restore_cache:
          keys:
            #:
            #: https://circleci.com/docs/2.0/caching/#restoring-cache
            #:
            #: Change 'v1' to 'v2', 'v3' etc., commit and push to force cache reset.
            #:
            #: Lookup cache based on the current branch and a timestamp. Allows
            #: to cache results of the very first build on the day (sanitized
            #: database dump, for example) and re-use it in all subsequent builds.
            - v1-db8-{{ .Branch }}-{{ checksum "/tmp/DB_CACHE_TIMESTAMP" }}
            #:
            #: Fallback to caching by branch name. Allows to use cache from the
            #: branch build on the previous day.
            - v1-db8-{{ .Branch }}-{{ checksum "/tmp/DB_CACHE_FALLBACK" }}
      #: Download database and run post DB download commands: build site and
      #: export the database. Note that configuration changes and DB updates
      #: are not applied, so we could cache the database as it was downloaded.
      - run:
          name: Download DB
          command: DOWNLOAD_POST_PROCESS="export SKIP_POST_DB_IMPORT=1 && ahoy build && ahoy export-db db.sql" ahoy download-db
          no_output_timeout: 20m
      - save_cache:
          key: v1-db8-{{ .Branch }}-{{ checksum "/tmp/DB_CACHE_TIMESTAMP" }}
          paths:
            - *db_cache_dir
  #;> !FRESH_INSTALL

  #; Build and test is a second step of the build. The testing is performed
  #; within the same job to save time on provisioning during the job.
  build:
    <<: *container_config
    parallelism: 2
    steps:
      - attach_workspace:
          at: /workspace
      - checkout
      - *step_process_codebase
      - *step_setup_remote_docker
      - restore_cache:
          keys:
            #:
            #: Use cached artifacts from previous builds of this branch ran at
            #: any time.
            #: https://circleci.com/docs/2.0/caching/#restoring-cache
            - v1-db8-{{ .Branch }}-
      - run:
          name: Build site
          command: ahoy build
          no_output_timeout: 20m
      - run:
          name: Lint code
          command: ahoy lint
      - run:
          name: Run tests
          command: BEHAT_PARALLEL_INDEX=$CIRCLE_NODE_INDEX ahoy test
      - run:
          name: Process test logs and artifacts
          command: |
            [ -n "$(docker-compose ps -q cli)" ] && [ -n "$(docker ps -q --no-trunc | grep "$(docker-compose ps -q cli)")" ] && (
              ahoy cli mkdir -p "${TEST_LOG_DIR}" && docker cp "$(docker-compose ps -q cli)":"${TEST_LOG_DIR}" "${TEST_LOG_DIR}"
              ahoy cli mkdir -p "${TEST_ARTIFACT_DIR}" && docker cp "$(docker-compose ps -q cli)":"${TEST_ARTIFACT_DIR}" "${TEST_ARTIFACT_DIR}"
            ) || true
          when: always
      - store_test_results:
          path: *test_log_dir
          when: always
      - store_artifacts:
          path: *test_artifact_dir
          when: always
      #:
      #: Persisting previously built application code artifact (without
      #: development dependencies) to use it in deployment job.
      - persist_to_workspace:
          root: /workspace
          paths:
            - code

  #;< DEPLOYMENT
  # Deploy primary branches.
  deploy: &job_deploy
    <<: *container_config
    steps:
      #:
      #: Workspace now contains previously built application code artifact.
      - attach_workspace:
          at: /workspace
      #:
      #: Add SSH key into "runner" container to have "push" access to remote
      #: repository.
      - add_ssh_keys:
          fingerprints:
            - *deploy_ssh_fingerprint
      - checkout
      - *step_process_codebase
      - run:
          command: ahoy deploy
          no_output_timeout: 30m
      - store_artifacts:
          path: *test_artifact_dir

  # Deploy tags.
  deploy_tags: &job_deploy_tags
    <<: *container_config
    steps:
      #:
      #: Workspace now contains previously built application code artifact.
      - attach_workspace:
          at: /workspace
      #:
      #: Add SSH key into "runner" container to have "push" access to remote
      #: repository.
      - add_ssh_keys:
          fingerprints:
            - *deploy_ssh_fingerprint
      - checkout
      - *step_process_codebase
      - run:
          command: DEPLOY_GIT_BRANCH="deployment/[tags:-]" ahoy deploy
          no_output_timeout: 30m
      - store_artifacts:
          path: *test_artifact_dir
  #;> DEPLOYMENT
  #;----------------------------------------------------------------------------
  #; DREVOPS development section. Will be removed during installation/update.
  #;----------------------------------------------------------------------------
  #;
  #; We are using CircleCI config file to both run the application tests (what
  #; a consumer site would use) and DrevOps' own tests (to make sure that
  #; this project is "buildable" at any time).
  #;
  #;< DREVOPS
  #; Test suite for DrevOps.
  drevops_test:
    <<: *container_config
    parallelism: 2
    steps:
      - checkout
      - *step_process_codebase
      - *step_setup_remote_docker
      - run:
          name: Run functional tests (long)
          command: .circleci/drevops-test.sh
          no_output_timeout: 30m

  drevops_test_deployment:
    <<: *container_config
    parallelism: 2
    steps:
      - checkout
      - *step_process_codebase
      - *step_setup_remote_docker
      - add_ssh_keys:
          fingerprints:
            - *deploy_ssh_fingerprint
      - attach_workspace:
          at: /workspace
      - run:
          name: Run deployment tests (long)
          command: .circleci/drevops-test-deployment.sh
          no_output_timeout: 30m

  # Deployment of feature branches and tags for DrevOps itself.
  drevops_deploy:
    <<: *job_deploy

  drevops_deploy_tags:
    <<: *job_deploy_tags
  #;> DREVOPS

#:###############################################################################
#: WORKFLOWS
#:###############################################################################
workflows:
  version: 2
  #:
  #: Main workflow. Runs for every push to the remote repository.
  main:
    jobs:
      - database:
          filters:
            tags:
              only: /.*/
      - build:
          #;< !FRESH_INSTALL
          requires:
            - database
          #;> !FRESH_INSTALL
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            branches:
              # Allowed branches:
              # - master, develop, ci, cisomething
              # - release/123, release/123.456, release/123.456.789, release/123.456.789-rc123
              # - hotfix/123, hotfix/123.456, hotfix/123.456.789
              # - feature/description, feature/123-description, but not feature/8.x-description or feature/7.x-description
              only: /master|develop|ci.*|(release\/)?[0-9]+(\.[0-9]+)+(-rc[0-9]+)?|(hotfix\/)?[0-9]+(\.[0-9]+)+(-rc[0-9]+)?|feature\/(?!7.x-|8.x-)[a-zA-z0-9\-\.\,]+/
            tags:
              ignore: /.*/
      - deploy_tags:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              # Allowed tags: 1, 123, 123.456, 123.456.789, 123.456.789-rc123
              only: /^[0-9]+(\.[0-9]+)+(-rc[0-9]+)?$/
#;------------------------------------------------------------------------
#; DREVOPS development section. Will be removed during installation/update.
#;------------------------------------------------------------------------
#;
#;< DREVOPS
#; Remove the code below in your project.
#; Run unit and functional tests for DrevOps.
      - drevops_test:
          filters:
            tags:
              only: /.*/
      #; Run deployment tests for DrevOps.
      - drevops_test_deployment:
          requires:
            - drevops_test
            - build
          filters:
            tags:
              only: /.*/
      #; Run actual deployment of DrevOps code to destination codebase (integration test).
      #; @see https://github.com/drevops/drevops-destination
      - drevops_deploy:
          requires:
            - build
            - drevops_test
          filters:
            branches:
              # Allowed branches: 7.x, 8.x, feature/7.x-description, feature/8.x-description
              only: /(?:7|8)\.x|feature\/(?:7|8)\.x[a-zA-z0-9\-\.\,]+/
            tags:
              ignore: /.*/
      #; Run actual deployment of DrevOps code to destination codebase (integration test).
      #; @see https://github.com/drevops/drevops-destination
      - drevops_deploy_tags:
          requires:
            - build
            - drevops_test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^(?:7|8)\.x\-[0-9]+\.[0-9]+(?:[A-z0-9\-])*$/
      #;> DREVOPS
