version: 2
jobs:
  # Fail fast if code style is incorrect.
  cs:
    docker:
      - image: circleci/php:7.0-cli

    steps:
      - checkout

      - restore_cache:
          paths:
            - ~/project/vendor
          key: composer-dependencies-{{ checksum "composer.json" }}

      - run: pwd
      - run: composer install

      - save_cache:
          paths:
            - ~/project/vendor
          key: composer-dependencies-{{ checksum "composer.json" }}

      - run: composer cs

  download_db:
    machine: true

    steps:
      - restore_cache:
          paths:
            - ~/project/.data
          key: data-{{ .Branch }}

      # Download DB dump from public URL to test Drupal-dev project.
      # Remove the line below in your project.
      - run: if [ ! -f .data/db.dist.sql ] ; then mkdir .data && curl -L https://goo.gl/WFtJbT -o .data/db.dist.sql; fi
      # [META] Uncomment the line below to download DB dump from FTP, using
      # variables set in Circle CI UI.
      # - run: if [ ! -f $BUILD_DIR/.data/db.dist.sql ] ; then mkdir $BUILD_DIR/.data && curl -u $FTP_USER:$FTP_PASS "ftp://$FTP_HOST/db_d7.dist.sql" -o $BUILD_DIR/.data/db.dist.sql; fi

      - save_cache:
          paths:
            - ~/project/.data
          key: data-{{ .Branch }}

  # Build and test the whole project.
  build_and_test:
    docker:
      - image: circleci/php:7.0-cli

    steps:
      - checkout

      - restore_cache:
          paths:
            - ~/project/vendor
          key: composer-dependencies-{{ checksum "composer.json" }}

      - run: composer install

      - save_cache:
          paths:
            - ~/project/vendor
          key: composer-dependencies-{{ checksum "composer.json" }}

      - run: composer cs

workflows:
  version: 2

  cs_and_build_and_test:
    jobs:
      - cs
      - download_db
      - build_and_test:
          requires:
            - cs
            - download_db
