version: '2.3'
services:
  mkdocs:
    build:
      context: .
      dockerfile: ./.utils/Dockerfile
    environment:
      LAGOON_LOCALDEV_HTTP_PORT: 8080
      DREVOPS_LOCALDEV_URL: drevops-docs.docker.amazee.io:8080
    networks:
      - amazeeio-network
      - default
    volumes: ### Removed in CI.
      - ${PWD}:/app  ### Removed in CI.
    ports:
      - 8080:8080
  linkchecker:
    image: jare/linkchecker

networks:
  amazeeio-network:
    external: true
