version: '2.3'
services:
  mkdocs:
    build:
      context: .
      dockerfile: ./.utils/Dockerfile
    environment:
      LAGOON_LOCALDEV_HTTP_PORT: 8000
    networks:
      - amazeeio-network
      - default
    ports:
      - 8000:8000
  linkchecker:
    image: jare/linkchecker

networks:
  amazeeio-network:
    external: true
