---
ahoyapi: v2

commands:
  build:
    usage: Build site
    cmd: |
      ahoy down
      (docker network prune -f > /dev/null && docker network inspect amazeeio-network > /dev/null || docker network create amazeeio-network)
      ahoy update
      ahoy up -- --build --force-recreate
      ahoy info

  up:
    usage: Build and start Docker containers.
    cmd: |
      docker compose up -d "$@" && \
      docker compose exec mkdocs sh -c "dockerize -wait tcp://mkdocs:8080 -timeout 1m"
      if docker compose logs | grep -q "\[Error\]"; then docker compose logs; exit 1; fi

  down:
    usage: Stop Docker containers and remove container, images, volumes and networks.
    cmd: "if [ -f \"docker-compose.yml\" ]; then docker compose down --volumes; fi"

  start:
    usage: Start existing Docker containers.
    cmd: docker compose start "$@"

  stop:
    usage: Stop running Docker containers.
    cmd: docker compose stop "$@"

  cli:
    usage: Start a shell or run a command inside the CLI service container.
    cmd: if \[ "${#}" -ne 0 \]; then docker compose exec -T mkdocs sh -c "$*"; else docker compose exec mkdocs sh; fi

  lint:
    usage: Lint site
    cmd: ./.utils/lint.sh

  test:
    usage: Test
    cmd: |
      ahoy test-scripts
      ahoy test-site

  test-scripts:
    usage: Test scripts
    cmd: ./.utils/test.sh

  test-site:
    usage: Test site
    cmd: docker compose run linkchecker http://mkdocs:8080 "$@"

  update:
    usage: Update docs
    cmd: ./.utils/update-docs.sh

  info:
    usage: Print information about this project.
    cmd: 'echo -n "Site local URL: http://" && ahoy cli "echo \${DREVOPS_LOCALDEV_URL}"'

  version:
    usage: MkDocs version
    cmd: docker compose run mkdocs --version

entrypoint:
  - bash
  - "-c"
  - "-e"
  - bash -e -c "$0" "$@"
  - '{{cmd}}'
  - '{{name}}'
