# This action is used for DrevOps maintenance. It will not be used in the scaffolded project.
name: DrevOps - Publish documentation

on:
  push:
    tags:
      - '*'
    branches:
      - develop
      - '**docs**'

jobs:
  drevops-publish-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install Ahoy
        run: os=$(uname -s | tr [:upper:] [:lower:]) && architecture=$(case $(uname -m) in x86_64 | amd64) echo "amd64" ;; aarch64 | arm64 | armv8) echo "arm64" ;; *) echo "amd64" ;; esac) && sudo wget -q https://github.com/ahoy-cli/ahoy/releases/latest/download/ahoy-bin-$os-$architecture -O /usr/local/bin/ahoy && sudo chown $USER /usr/local/bin/ahoy && chmod +x /usr/local/bin/ahoy

      - name: Install Aspell
        run: sudo apt-get update -y && sudo apt-get install -y aspell

      - name: Setup PHP
        uses: shivammathur/setup-php@v2

      - name: Build site
        working-directory: .drevops/docs
        run: ahoy build

      - name: Check spelling
        working-directory: .drevops/docs
        run: ahoy lint

      - name: Run tests
        working-directory: .drevops/docs
        run: ahoy test

      - name: Setup SSH private key
        uses: webfactory/ssh-agent@v0.9.0
        with:
            ssh-private-key: ${{ secrets.DOCS_PUBLISH_SSH_PRIVATE_KEY }}

      - name: Publish docs
        run: |
          cd .drevops/docs
          export DOCS_PUBLISH_REMOTE_URL=git@github.com:drevops/drevops_docs.git
          export DOCS_PUBLISH_SRC_TAG=${{ github.ref_type == 'tag' && github.ref_name || '' }}
          export DOCS_PUBLISH_SRC_BRANCH=${{ github.ref_type == 'branch' && github.ref_name || '' }}
          export DOCS_PUBLISH_CANARY_BRANCH="develop"
          export DOCS_PUBLISH_COMMIT_MESSAGE="Automatically pushed from drevops/drevops"
          export DOCS_PUBLISH_GIT_EMAIL="deployer@drevops.com"
          ./.utils/publish.sh
